version: "3.8"

services:
  postgres-comments:
    image: postgres:alpine
    ports:
      - "5436:5432"
    container_name: "postgres_comments_api"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  postgresql:
